version: '3.9'

services:

  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: autopartsdb
    ports:
      - 5432:5432