"""add created_by field in manufacturers table

Revision ID: 33872b78d4ab
Revises: 92d27b5632e9
Create Date: 2024-11-19 20:54:10.726871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33872b78d4ab'
down_revision: Union[str, None] = '92d27b5632e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'manufacturers', 'users', ['created_by'], ['pk'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manufacturers', type_='foreignkey')
    op.drop_column('manufacturers', 'created_by')
    # ### end Alembic commands ###
