"""add updated_by field in manufacturers table

Revision ID: 81f362aba276
Revises: 33872b78d4ab
Create Date: 2024-11-19 20:54:57.186034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81f362aba276'
down_revision: Union[str, None] = '33872b78d4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('updated_by', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'manufacturers', 'users', ['updated_by'], ['pk'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manufacturers', type_='foreignkey')
    op.drop_column('manufacturers', 'updated_by')
    # ### end Alembic commands ###
