"""add table part

Revision ID: 856864d412e7
Revises: a8043100d8b7
Create Date: 2024-12-16 17:53:30.272291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '856864d412e7'
down_revision: Union[str, None] = 'a8043100d8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('vehicle_pk', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.pk'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.pk'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_pk'], ['vehicles.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_parts_pk'), 'parts', ['pk'], unique=False)
    op.add_column('vehicles', sa.Column('part_pk', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'vehicles', 'parts', ['part_pk'], ['pk'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'part_pk')
    op.drop_index(op.f('ix_parts_pk'), table_name='parts')
    op.drop_table('parts')
    # ### end Alembic commands ###
