"""add vehicles table

Revision ID: a8043100d8b7
Revises: 81f362aba276
Create Date: 2024-12-16 15:22:51.795097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a8043100d8b7'
down_revision: Union[str, None] = '81f362aba276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('transmission', sa.Enum('automatic', 'manual', name='transmission'), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('manufacturer_pk', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.pk'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manufacturer_pk'], ['manufacturers.pk'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_vehicles_pk'), 'vehicles', ['pk'], unique=False)
    op.drop_constraint('manufacturers_updated_by_fkey', 'manufacturers', type_='foreignkey')
    op.drop_constraint('manufacturers_created_by_fkey', 'manufacturers', type_='foreignkey')
    op.create_foreign_key(None, 'manufacturers', 'users', ['updated_by'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'manufacturers', 'users', ['created_by'], ['pk'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manufacturers', type_='foreignkey')
    op.drop_constraint(None, 'manufacturers', type_='foreignkey')
    op.create_foreign_key('manufacturers_created_by_fkey', 'manufacturers', 'users', ['created_by'], ['pk'])
    op.create_foreign_key('manufacturers_updated_by_fkey', 'manufacturers', 'users', ['updated_by'], ['pk'])
    op.drop_index(op.f('ix_vehicles_pk'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
